# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-22 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enduser',
            old_name='location',
            new_name='lat',
        ),
        migrations.AddField(
            model_name='enduser',
            name='lng',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
